name: "Tina's Dog Walking"
description: "Something descriptive here"
url: "http://kalenenc.github.io/"
# url: "https://github.com/kalenenc/dog-website"
baseurl: /

#paginate: 10

markdown: kramdown
permalink: pretty
# highlighter: pygments
