name: "Tina's Dog Walking"
description: "Something descriptive here"

#url: "http://127.0.0.1:4000/"
url: "http://kalenenc.github.io/dog-website/"

#paginate: 10

markdown: kramdown
permalink: pretty
# highlighter: pygments
